name: Kernel build
on: push

jobs:
  build-kernel:
    name: Build kernel RPM
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Build the kernel
        run: |
          ./scripts/prepare-github-builder.sh
          ./scripts/run-kernel-builder.sh

      - name: Short system report
        run: |
          df -h
          sudo du -sh /var/lib/docker
          ls -al RPMS SRPMS BUILD

      - name: Upload RPMS as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: kernel-rpms
          path: |
            RPMS/**/*
